# Welcome to Jekyll!

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Performance + Technology 2021"
email: your-email@example.com
description: "Site for Parsons Performance + Technology Studio 2021. Includes syllabus, outlines for exercises and meetings each day, and crucial links."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://performancetechnology.github.io" # the base hostname & protocol for your site, e.g. http://example.com
# github_username: performancetechnology
# class_zoom: https://NewSchool.zoom.us/j/93521164740?pwd=YzlnTUdKdUY1TTVBai93SmgxR0FRZz09
# class_slack:

header_pages:
  - resources.md
  - day01.md
  - day02.md
  - day03.md
  - day04.md
  # - day05.md

# Build settings
# markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
# exclude:
#   - TODO.md
#   - README.md
